deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    # ⬇️ Create kubeconfig from GitHub Secret
    - name: Setup kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

    - name: Test cluster connection
      run: kubectl cluster-info

    - name: Update image tag
      run: |
        sed -i "s|karthickkatty1/my-app:latest|karthickkatty1/my-app:${{ github.sha }}|g" k8s/deployment.yaml

    - name: Check updated deployment.yaml
      run: cat k8s/deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Verify Deployment
      run: kubectl get pods -o wide
